// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spain_cup_03_11_2025;

#nullable disable

namespace Spain_cup_03_11_2025.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104172414_Matches_Players_delete")]
    partial class Matches_Players_delete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Club", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Club_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goals_Lost")
                        .HasColumnType("int");

                    b.Property<int>("Goals_scored")
                        .HasColumnType("int");

                    b.Property<int>("Lose")
                        .HasColumnType("int");

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.Property<int>("Player_id")
                        .HasColumnType("int");

                    b.Property<int>("Tie")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MatchID");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("club1_id")
                        .HasColumnType("int");

                    b.Property<int>("club1_scored")
                        .HasColumnType("int");

                    b.Property<int>("club2_id")
                        .HasColumnType("int");

                    b.Property<int>("club2_scored")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClubID")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClubID");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Club", b =>
                {
                    b.HasOne("Spain_cup_03_11_2025.DAL.Entities.Match", "Match")
                        .WithMany("Clubs")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Player", b =>
                {
                    b.HasOne("Spain_cup_03_11_2025.DAL.Entities.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Match", b =>
                {
                    b.Navigation("Clubs");
                });
#pragma warning restore 612, 618
        }
    }
}
