// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spain_cup_03_11_2025;

#nullable disable

namespace Spain_cup_03_11_2025.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104225341_Finalversion3")]
    partial class Finalversion3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Club", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Club_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goals_Lost")
                        .HasColumnType("int");

                    b.Property<int>("Goals_scored")
                        .HasColumnType("int");

                    b.Property<int>("Lose")
                        .HasColumnType("int");

                    b.Property<int>("Tie")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Club_Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Club1_id")
                        .HasColumnType("int");

                    b.Property<int>("Club2_id")
                        .HasColumnType("int");

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Club1_id");

                    b.HasIndex("Club2_id");

                    b.HasIndex("MatchID");

                    b.ToTable("Club_Matches");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Goal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MatchID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("club1_scored")
                        .HasColumnType("int");

                    b.Property<int>("club2_scored")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClubID")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MatchID")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClubID");

                    b.HasIndex("MatchID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Club_Match", b =>
                {
                    b.HasOne("Spain_cup_03_11_2025.DAL.Entities.Club", "Club1")
                        .WithMany("Club1_Matches")
                        .HasForeignKey("Club1_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spain_cup_03_11_2025.DAL.Entities.Club", "Club2")
                        .WithMany("Club2_Matches")
                        .HasForeignKey("Club2_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spain_cup_03_11_2025.DAL.Entities.Match", "Match")
                        .WithMany("Club_Match")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club1");

                    b.Navigation("Club2");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Goal", b =>
                {
                    b.HasOne("Spain_cup_03_11_2025.DAL.Entities.Match", "Match")
                        .WithMany("Goals")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spain_cup_03_11_2025.DAL.Entities.Player", "Player")
                        .WithMany("Goals")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Player", b =>
                {
                    b.HasOne("Spain_cup_03_11_2025.DAL.Entities.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spain_cup_03_11_2025.DAL.Entities.Match", null)
                        .WithMany("playersscored")
                        .HasForeignKey("MatchID");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Club", b =>
                {
                    b.Navigation("Club1_Matches");

                    b.Navigation("Club2_Matches");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Match", b =>
                {
                    b.Navigation("Club_Match");

                    b.Navigation("Goals");

                    b.Navigation("playersscored");
                });

            modelBuilder.Entity("Spain_cup_03_11_2025.DAL.Entities.Player", b =>
                {
                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
